@baseUrl = http://localhost:3002

### register
# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "Teste",
  "email": "teste1@gmail.com",
  "password": "123456"
}

###

### authenticate
# @name authenticate
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "teste1@gmail.com",
  "password": "123456"
}

###

@accessToken = {{ authenticate.response.body.access_token }}
@refreshToken = {{ authenticate.response.body.refresh_token }}

###

### refresh
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}
