@baseUrl = http://localhost:3002
@authToken = {{ authenticate.response.body.acess_token }}

# @name create_acount
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "Teste",
    "email": "teste1@gmail.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "teste1@gmail.com",
    "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/auth/refresh
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Nova pergunta 1",
    "content": "Conteudo"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_question
PUT {{baseUrl}}/questions/a3cf524c-9311-4c27-87c8-f4c2ff4ae2e9
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Nova pergunta 01",
    "content": "Conteudo"
}